/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminGenresRouteImport } from './routes/admin.genres'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminTitlesRouteImport } from './routes/admin.titles'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as AdminLoginConfirmRouteImport } from './routes/admin.login_.confirm'
import { Route as AdminTitlesIndexRouteImport } from './routes/admin.titles.index'
import { Route as AdminTitlesIdRouteImport } from './routes/admin.titles.$id'
import { Route as AdminTitlesNewRouteImport } from './routes/admin.titles.new'
import { Route as TitleSlugIndexRouteImport } from './routes/title.$slug.index'
import { Route as AdminTitlesIdIndexRouteImport } from './routes/admin.titles.$id.index'
import { Route as AdminTitlesIdChaptersRouteImport } from './routes/admin.titles.$id.chapters'
import { Route as TitleSlugChapterNumberRouteImport } from './routes/title.$slug.chapter.$number'
import { Route as AdminTitlesIdChaptersCidRouteImport } from './routes/admin.titles.$id.chapters.$cid'
import { Route as AdminTitlesIdChaptersImportRouteImport } from './routes/admin.titles.$id.chapters.import'
import { Route as AdminTitlesIdChaptersCidPagesRouteImport } from './routes/admin.titles.$id.chapters.$cid_.pages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitlesRoute = AdminTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => AdminRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginConfirmRoute = AdminLoginConfirmRouteImport.update({
  id: '/login_/confirm',
  path: '/login/confirm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitlesIndexRoute = AdminTitlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const AdminTitlesIdRoute = AdminTitlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const AdminTitlesNewRoute = AdminTitlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const TitleSlugIndexRoute = TitleSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TitleSlugRoute,
} as any)
const AdminTitlesIdIndexRoute = AdminTitlesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTitlesIdRoute,
} as any)
const AdminTitlesIdChaptersRoute = AdminTitlesIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminTitlesIdRoute,
} as any)
const TitleSlugChapterNumberRoute = TitleSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => TitleSlugRoute,
} as any)
const AdminTitlesIdChaptersCidRoute =
  AdminTitlesIdChaptersCidRouteImport.update({
    id: '/$cid',
    path: '/$cid',
    getParentRoute: () => AdminTitlesIdChaptersRoute,
  } as any)
const AdminTitlesIdChaptersImportRoute =
  AdminTitlesIdChaptersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AdminTitlesIdChaptersRoute,
  } as any)
const AdminTitlesIdChaptersCidPagesRoute =
  AdminTitlesIdChaptersCidPagesRouteImport.update({
    id: '/$cid_/pages',
    path: '/$cid/pages',
    getParentRoute: () => AdminTitlesIdChaptersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/titles': typeof AdminTitlesRouteWithChildren
  '/s/$token': typeof STokenRoute
  '/title/$slug': typeof TitleSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/login/confirm': typeof AdminLoginConfirmRoute
  '/admin/titles/$id': typeof AdminTitlesIdRouteWithChildren
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/title/$slug/': typeof TitleSlugIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id/': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
  '/admin/titles/$id/chapters/import': typeof AdminTitlesIdChaptersImportRoute
  '/admin/titles/$id/chapters/$cid/pages': typeof AdminTitlesIdChaptersCidPagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/s/$token': typeof STokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login/confirm': typeof AdminLoginConfirmRoute
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles': typeof AdminTitlesIndexRoute
  '/title/$slug': typeof TitleSlugIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
  '/admin/titles/$id/chapters/import': typeof AdminTitlesIdChaptersImportRoute
  '/admin/titles/$id/chapters/$cid/pages': typeof AdminTitlesIdChaptersCidPagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/titles': typeof AdminTitlesRouteWithChildren
  '/s/$token': typeof STokenRoute
  '/title/$slug': typeof TitleSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/login_/confirm': typeof AdminLoginConfirmRoute
  '/admin/titles/$id': typeof AdminTitlesIdRouteWithChildren
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/title/$slug/': typeof TitleSlugIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id/': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
  '/admin/titles/$id/chapters/import': typeof AdminTitlesIdChaptersImportRoute
  '/admin/titles/$id/chapters/$cid_/pages': typeof AdminTitlesIdChaptersCidPagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advertise'
    | '/admin/ads'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/requests'
    | '/admin/titles'
    | '/s/$token'
    | '/title/$slug'
    | '/admin/'
    | '/admin/login/confirm'
    | '/admin/titles/$id'
    | '/admin/titles/new'
    | '/admin/titles/'
    | '/title/$slug/'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id/'
    | '/admin/titles/$id/chapters/$cid'
    | '/admin/titles/$id/chapters/import'
    | '/admin/titles/$id/chapters/$cid/pages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/admin/ads'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/requests'
    | '/s/$token'
    | '/admin'
    | '/admin/login/confirm'
    | '/admin/titles/new'
    | '/admin/titles'
    | '/title/$slug'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id'
    | '/admin/titles/$id/chapters/$cid'
    | '/admin/titles/$id/chapters/import'
    | '/admin/titles/$id/chapters/$cid/pages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advertise'
    | '/admin/ads'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/requests'
    | '/admin/titles'
    | '/s/$token'
    | '/title/$slug'
    | '/admin/'
    | '/admin/login_/confirm'
    | '/admin/titles/$id'
    | '/admin/titles/new'
    | '/admin/titles/'
    | '/title/$slug/'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id/'
    | '/admin/titles/$id/chapters/$cid'
    | '/admin/titles/$id/chapters/import'
    | '/admin/titles/$id/chapters/$cid_/pages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  STokenRoute: typeof STokenRoute
  TitleSlugRoute: typeof TitleSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titles': {
      id: '/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AdminTitlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login_/confirm': {
      id: '/admin/login_/confirm'
      path: '/login/confirm'
      fullPath: '/admin/login/confirm'
      preLoaderRoute: typeof AdminLoginConfirmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titles/': {
      id: '/admin/titles/'
      path: '/'
      fullPath: '/admin/titles/'
      preLoaderRoute: typeof AdminTitlesIndexRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/admin/titles/$id': {
      id: '/admin/titles/$id'
      path: '/$id'
      fullPath: '/admin/titles/$id'
      preLoaderRoute: typeof AdminTitlesIdRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/admin/titles/new': {
      id: '/admin/titles/new'
      path: '/new'
      fullPath: '/admin/titles/new'
      preLoaderRoute: typeof AdminTitlesNewRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/title/$slug/': {
      id: '/title/$slug/'
      path: '/'
      fullPath: '/title/$slug/'
      preLoaderRoute: typeof TitleSlugIndexRouteImport
      parentRoute: typeof TitleSlugRoute
    }
    '/admin/titles/$id/': {
      id: '/admin/titles/$id/'
      path: '/'
      fullPath: '/admin/titles/$id/'
      preLoaderRoute: typeof AdminTitlesIdIndexRouteImport
      parentRoute: typeof AdminTitlesIdRoute
    }
    '/admin/titles/$id/chapters': {
      id: '/admin/titles/$id/chapters'
      path: '/chapters'
      fullPath: '/admin/titles/$id/chapters'
      preLoaderRoute: typeof AdminTitlesIdChaptersRouteImport
      parentRoute: typeof AdminTitlesIdRoute
    }
    '/title/$slug/chapter/$number': {
      id: '/title/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/title/$slug/chapter/$number'
      preLoaderRoute: typeof TitleSlugChapterNumberRouteImport
      parentRoute: typeof TitleSlugRoute
    }
    '/admin/titles/$id/chapters/$cid': {
      id: '/admin/titles/$id/chapters/$cid'
      path: '/$cid'
      fullPath: '/admin/titles/$id/chapters/$cid'
      preLoaderRoute: typeof AdminTitlesIdChaptersCidRouteImport
      parentRoute: typeof AdminTitlesIdChaptersRoute
    }
    '/admin/titles/$id/chapters/import': {
      id: '/admin/titles/$id/chapters/import'
      path: '/import'
      fullPath: '/admin/titles/$id/chapters/import'
      preLoaderRoute: typeof AdminTitlesIdChaptersImportRouteImport
      parentRoute: typeof AdminTitlesIdChaptersRoute
    }
    '/admin/titles/$id/chapters/$cid_/pages': {
      id: '/admin/titles/$id/chapters/$cid_/pages'
      path: '/$cid/pages'
      fullPath: '/admin/titles/$id/chapters/$cid/pages'
      preLoaderRoute: typeof AdminTitlesIdChaptersCidPagesRouteImport
      parentRoute: typeof AdminTitlesIdChaptersRoute
    }
  }
}

interface AdminTitlesIdChaptersRouteChildren {
  AdminTitlesIdChaptersCidRoute: typeof AdminTitlesIdChaptersCidRoute
  AdminTitlesIdChaptersImportRoute: typeof AdminTitlesIdChaptersImportRoute
  AdminTitlesIdChaptersCidPagesRoute: typeof AdminTitlesIdChaptersCidPagesRoute
}

const AdminTitlesIdChaptersRouteChildren: AdminTitlesIdChaptersRouteChildren = {
  AdminTitlesIdChaptersCidRoute: AdminTitlesIdChaptersCidRoute,
  AdminTitlesIdChaptersImportRoute: AdminTitlesIdChaptersImportRoute,
  AdminTitlesIdChaptersCidPagesRoute: AdminTitlesIdChaptersCidPagesRoute,
}

const AdminTitlesIdChaptersRouteWithChildren =
  AdminTitlesIdChaptersRoute._addFileChildren(
    AdminTitlesIdChaptersRouteChildren,
  )

interface AdminTitlesIdRouteChildren {
  AdminTitlesIdChaptersRoute: typeof AdminTitlesIdChaptersRouteWithChildren
  AdminTitlesIdIndexRoute: typeof AdminTitlesIdIndexRoute
}

const AdminTitlesIdRouteChildren: AdminTitlesIdRouteChildren = {
  AdminTitlesIdChaptersRoute: AdminTitlesIdChaptersRouteWithChildren,
  AdminTitlesIdIndexRoute: AdminTitlesIdIndexRoute,
}

const AdminTitlesIdRouteWithChildren = AdminTitlesIdRoute._addFileChildren(
  AdminTitlesIdRouteChildren,
)

interface AdminTitlesRouteChildren {
  AdminTitlesIdRoute: typeof AdminTitlesIdRouteWithChildren
  AdminTitlesNewRoute: typeof AdminTitlesNewRoute
  AdminTitlesIndexRoute: typeof AdminTitlesIndexRoute
}

const AdminTitlesRouteChildren: AdminTitlesRouteChildren = {
  AdminTitlesIdRoute: AdminTitlesIdRouteWithChildren,
  AdminTitlesNewRoute: AdminTitlesNewRoute,
  AdminTitlesIndexRoute: AdminTitlesIndexRoute,
}

const AdminTitlesRouteWithChildren = AdminTitlesRoute._addFileChildren(
  AdminTitlesRouteChildren,
)

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminGenresRoute: typeof AdminGenresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTitlesRoute: typeof AdminTitlesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLoginConfirmRoute: typeof AdminLoginConfirmRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminGenresRoute: AdminGenresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTitlesRoute: AdminTitlesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminLoginConfirmRoute: AdminLoginConfirmRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TitleSlugRouteChildren {
  TitleSlugIndexRoute: typeof TitleSlugIndexRoute
  TitleSlugChapterNumberRoute: typeof TitleSlugChapterNumberRoute
}

const TitleSlugRouteChildren: TitleSlugRouteChildren = {
  TitleSlugIndexRoute: TitleSlugIndexRoute,
  TitleSlugChapterNumberRoute: TitleSlugChapterNumberRoute,
}

const TitleSlugRouteWithChildren = TitleSlugRoute._addFileChildren(
  TitleSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  STokenRoute: STokenRoute,
  TitleSlugRoute: TitleSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
