/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminGenresRouteImport } from './routes/admin.genres'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminTitlesRouteImport } from './routes/admin.titles'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as AdminTitlesIndexRouteImport } from './routes/admin.titles.index'
import { Route as AdminTitlesIdRouteImport } from './routes/admin.titles.$id'
import { Route as AdminTitlesNewRouteImport } from './routes/admin.titles.new'
import { Route as AdminTitlesIdIndexRouteImport } from './routes/admin.titles.$id.index'
import { Route as AdminTitlesIdChaptersRouteImport } from './routes/admin.titles.$id.chapters'
import { Route as TitleSlugChapterNumberRouteImport } from './routes/title.$slug.chapter.$number'
import { Route as AdminTitlesIdChaptersCidRouteImport } from './routes/admin.titles.$id.chapters.$cid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitlesRoute = AdminTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => AdminRoute,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTitlesIndexRoute = AdminTitlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const AdminTitlesIdRoute = AdminTitlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const AdminTitlesNewRoute = AdminTitlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTitlesRoute,
} as any)
const AdminTitlesIdIndexRoute = AdminTitlesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTitlesIdRoute,
} as any)
const AdminTitlesIdChaptersRoute = AdminTitlesIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminTitlesIdRoute,
} as any)
const TitleSlugChapterNumberRoute = TitleSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => TitleSlugRoute,
} as any)
const AdminTitlesIdChaptersCidRoute =
  AdminTitlesIdChaptersCidRouteImport.update({
    id: '/$cid',
    path: '/$cid',
    getParentRoute: () => AdminTitlesIdChaptersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/titles': typeof AdminTitlesRouteWithChildren
  '/title/$slug': typeof TitleSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/titles/$id': typeof AdminTitlesIdRouteWithChildren
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id/': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/title/$slug': typeof TitleSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles': typeof AdminTitlesIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/titles': typeof AdminTitlesRouteWithChildren
  '/title/$slug': typeof TitleSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/titles/$id': typeof AdminTitlesIdRouteWithChildren
  '/admin/titles/new': typeof AdminTitlesNewRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/admin/titles/$id/chapters': typeof AdminTitlesIdChaptersRouteWithChildren
  '/title/$slug/chapter/$number': typeof TitleSlugChapterNumberRoute
  '/admin/titles/$id/': typeof AdminTitlesIdIndexRoute
  '/admin/titles/$id/chapters/$cid': typeof AdminTitlesIdChaptersCidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/titles'
    | '/title/$slug'
    | '/admin/'
    | '/admin/titles/$id'
    | '/admin/titles/new'
    | '/admin/titles/'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id/'
    | '/admin/titles/$id/chapters/$cid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/genres'
    | '/admin/login'
    | '/title/$slug'
    | '/admin'
    | '/admin/titles/new'
    | '/admin/titles'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id'
    | '/admin/titles/$id/chapters/$cid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/titles'
    | '/title/$slug'
    | '/admin/'
    | '/admin/titles/$id'
    | '/admin/titles/new'
    | '/admin/titles/'
    | '/admin/titles/$id/chapters'
    | '/title/$slug/chapter/$number'
    | '/admin/titles/$id/'
    | '/admin/titles/$id/chapters/$cid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TitleSlugRoute: typeof TitleSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titles': {
      id: '/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AdminTitlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/titles/': {
      id: '/admin/titles/'
      path: '/'
      fullPath: '/admin/titles/'
      preLoaderRoute: typeof AdminTitlesIndexRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/admin/titles/$id': {
      id: '/admin/titles/$id'
      path: '/$id'
      fullPath: '/admin/titles/$id'
      preLoaderRoute: typeof AdminTitlesIdRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/admin/titles/new': {
      id: '/admin/titles/new'
      path: '/new'
      fullPath: '/admin/titles/new'
      preLoaderRoute: typeof AdminTitlesNewRouteImport
      parentRoute: typeof AdminTitlesRoute
    }
    '/admin/titles/$id/': {
      id: '/admin/titles/$id/'
      path: '/'
      fullPath: '/admin/titles/$id/'
      preLoaderRoute: typeof AdminTitlesIdIndexRouteImport
      parentRoute: typeof AdminTitlesIdRoute
    }
    '/admin/titles/$id/chapters': {
      id: '/admin/titles/$id/chapters'
      path: '/chapters'
      fullPath: '/admin/titles/$id/chapters'
      preLoaderRoute: typeof AdminTitlesIdChaptersRouteImport
      parentRoute: typeof AdminTitlesIdRoute
    }
    '/title/$slug/chapter/$number': {
      id: '/title/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/title/$slug/chapter/$number'
      preLoaderRoute: typeof TitleSlugChapterNumberRouteImport
      parentRoute: typeof TitleSlugRoute
    }
    '/admin/titles/$id/chapters/$cid': {
      id: '/admin/titles/$id/chapters/$cid'
      path: '/$cid'
      fullPath: '/admin/titles/$id/chapters/$cid'
      preLoaderRoute: typeof AdminTitlesIdChaptersCidRouteImport
      parentRoute: typeof AdminTitlesIdChaptersRoute
    }
  }
}

interface AdminTitlesIdChaptersRouteChildren {
  AdminTitlesIdChaptersCidRoute: typeof AdminTitlesIdChaptersCidRoute
}

const AdminTitlesIdChaptersRouteChildren: AdminTitlesIdChaptersRouteChildren = {
  AdminTitlesIdChaptersCidRoute: AdminTitlesIdChaptersCidRoute,
}

const AdminTitlesIdChaptersRouteWithChildren =
  AdminTitlesIdChaptersRoute._addFileChildren(
    AdminTitlesIdChaptersRouteChildren,
  )

interface AdminTitlesIdRouteChildren {
  AdminTitlesIdChaptersRoute: typeof AdminTitlesIdChaptersRouteWithChildren
  AdminTitlesIdIndexRoute: typeof AdminTitlesIdIndexRoute
}

const AdminTitlesIdRouteChildren: AdminTitlesIdRouteChildren = {
  AdminTitlesIdChaptersRoute: AdminTitlesIdChaptersRouteWithChildren,
  AdminTitlesIdIndexRoute: AdminTitlesIdIndexRoute,
}

const AdminTitlesIdRouteWithChildren = AdminTitlesIdRoute._addFileChildren(
  AdminTitlesIdRouteChildren,
)

interface AdminTitlesRouteChildren {
  AdminTitlesIdRoute: typeof AdminTitlesIdRouteWithChildren
  AdminTitlesNewRoute: typeof AdminTitlesNewRoute
  AdminTitlesIndexRoute: typeof AdminTitlesIndexRoute
}

const AdminTitlesRouteChildren: AdminTitlesRouteChildren = {
  AdminTitlesIdRoute: AdminTitlesIdRouteWithChildren,
  AdminTitlesNewRoute: AdminTitlesNewRoute,
  AdminTitlesIndexRoute: AdminTitlesIndexRoute,
}

const AdminTitlesRouteWithChildren = AdminTitlesRoute._addFileChildren(
  AdminTitlesRouteChildren,
)

interface AdminRouteChildren {
  AdminGenresRoute: typeof AdminGenresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTitlesRoute: typeof AdminTitlesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGenresRoute: AdminGenresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTitlesRoute: AdminTitlesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TitleSlugRouteChildren {
  TitleSlugChapterNumberRoute: typeof TitleSlugChapterNumberRoute
}

const TitleSlugRouteChildren: TitleSlugRouteChildren = {
  TitleSlugChapterNumberRoute: TitleSlugChapterNumberRoute,
}

const TitleSlugRouteWithChildren = TitleSlugRoute._addFileChildren(
  TitleSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TitleSlugRoute: TitleSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
